variable ec2_type {}
variable tag_ec2 {}
variable associate_public_ip_address {}
variable key_name {}
variable volume_type {}
variable volume_size {}
variable volume_delete_on_termination {}
variable "swap-gib" {}
variable "availability_zone" {}
variable "vpc_security_group_ids" {}